# theme
theme = "./gruvbox"

[editor]
line-number = "relative"
mouse = false
color-modes = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "╎", "┆", "▏", "⸽"
skip-levels = 1
